version: 2.0
jobs: 
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "going to npm install"
      - run: npm install
      - run: CI=true npm run build 
  tests:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "going to run tests"
      - run: npm install
      - run: npm test
  useless_job:
    steps:
      - checkout
      - run: echo "hellloooo this is so useless"
workflows: 
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally