version: 2.0
jobs: 
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  sally:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "double trouble baby"
workflows: 
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally